spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    username:root
    password: root
    url: jdbc:mysql:///tmall_springboot?characterEncoding=utf8
    jpa:
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true


  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    servlet:
      content-type: text/html
    cache: false


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB





server:
  servlet:
    context-path: /tmall_springboot

